import jsPDF from 'jspdf';
import { FormData } from '@/types/form';

export const exportToPDF = (formData: FormData) => {
  const doc = new jsPDF();
  
  // Set up the document
  doc.setFontSize(20);
  doc.text('HighBar Planner - Personalized Fitness & Nutrition Plan', 20, 30);
  
  doc.setFontSize(14);
  doc.text(`Generated for: ${formData.name || 'User'}`, 20, 50);
  doc.text(`Goal: ${formData.goal} weight`, 20, 65);
  doc.text(`Timeframe: ${formData.timeframe.replace('w', ' weeks')}`, 20, 80);
  
  // Personal Information
  doc.setFontSize(16);
  doc.text('Personal Information', 20, 105);
  doc.setFontSize(12);
  doc.text(`Age: ${formData.age}`, 20, 120);
  doc.text(`Gender: ${formData.gender}`, 20, 135);
  doc.text(`Weight: ${formData.weight.value} ${formData.weight.unit}`, 20, 150);
  doc.text(`Height: ${formData.height.value} ${formData.height.unit}`, 20, 165);
  doc.text(`Activity Level: ${formData.activity_level}`, 20, 180);
  
  // Preferences
  doc.setFontSize(16);
  doc.text('Preferences', 20, 205);
  doc.setFontSize(12);
  doc.text(`Diet Type: ${formData.diet_type}`, 20, 220);
  doc.text(`Exercise Preference: ${formData.exercise_preference || 'Not specified'}`, 20, 235);
  doc.text(`Equipment: ${formData.equipment || 'Not specified'}`, 20, 250);
  
  if (formData.allergies && formData.allergies.length > 0) {
    doc.text(`Allergies: ${formData.allergies.join(', ')}`, 20, 265);
  }
  
  // Add a new page for the plan details
  doc.addPage();
  
  // Sample Plan
  doc.setFontSize(16);
  doc.text('Sample Weekly Plan', 20, 30);
  
  doc.setFontSize(14);
  doc.text('Daily Nutrition Guidelines:', 20, 55);
  doc.setFontSize(12);
  
  const nutritionItems = [
    'Breakfast: Focus on protein and complex carbs',
    'Lunch: Balanced meal with lean protein and vegetables',
    'Dinner: Light protein with plenty of vegetables',
    'Snacks: Healthy options like nuts, fruits, or yogurt'
  ];
  
  nutritionItems.forEach((item, index) => {
    doc.text(`• ${item}`, 25, 70 + (index * 15));
  });
  
  doc.setFontSize(14);
  doc.text('Weekly Workout Schedule:', 20, 140);
  doc.setFontSize(12);
  
  const workoutItems = [
    'Monday: Upper body strength training',
    'Tuesday: Cardiovascular exercise (30 minutes)',
    'Wednesday: Lower body strength training',
    'Thursday: Active recovery or yoga',
    'Friday: Full body circuit training',
    'Weekend: Outdoor activity or rest'
  ];
  
  workoutItems.forEach((item, index) => {
    doc.text(`• ${item}`, 25, 155 + (index * 15));
  });
  
  // Footer
  doc.setFontSize(10);
  doc.text('This plan is general guidance and does not replace professional medical advice.', 20, 270);
  doc.text('Generated by HighBar Planner', 20, 280);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 290);
  
  // Download the PDF
  const filename = `Nutrition-Fitness-Plan_${formData.name || 'User'}_${formData.goal}_${formData.timeframe}.pdf`;
  doc.save(filename);
};